version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
