version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 20

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60

